CREATE OR REPLACE TYPE name_varray IS VARRAY (10) OF VARCHAR2 (100)
/

CREATE OR REPLACE TYPE number_varray IS VARRAY (10) OF NUMBER
/

CREATE TABLE compensation (last_name VARCHAR2 (100), salary NUMBER)
/

